### PR TITLE
Copying fixes

### LINKED ISSUE #79: Newlines added when copying long string spanning multiple lines
Thanks for making this great tool! We recently started using mprocs for a developer playground that runs a handful of services at the same time and has a shell to interact with these services.

One problem is that when I select a long string that spans multiple lines (but doesn't contain any newlines itself) and press "c" to copy it

image

and then paste the resulting string, it now contains newlines which weren't present in the original string:

```
AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABCEugU0FOLagwr2NaNai2VNvDxe0vfNXss7bfggLQVK2wa1W5
PmtX7Dm72XyraGBSljmIadzJagAwofdsWXYDdPi0ErRGfwOs/Qp9D9RZYLGetUCm46xl3Z6dR0f55+RGSLQEJ9atIW9
JJmJOPYc/lg==
```

So I can't paste this back into another command without manually editing out the newlines myself.

I'm on m1 mac using default terminal app. Same thing happens if my shell is `bash` or `fish`.

### PR DESCRIPTION
**Pull request by Maan2003**
fixes #79 https://github.com/fedimint/fedimint/issues/2300

### CODE REVIEW

File: src/clipboard.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@ fn detect_copy_provider() -> Provider {
   // Wayland
   if std::env::var("WAYLAND_DISPLAY").is_ok() {
     if let Some(provider) =
-      check_prog("wl-copy", &["--foreground", "--type", "text/plain"])
```
Comment (pvolok) [inline src/clipboard.rs:33]: Thank you for the PR! What was the reason for removing this? If I'm not mistaken, there was a problem without that argument. But I can't remember for sure.

Comment (Maan2003) [reply src/clipboard.rs:33]: with --foreground, mprocs process just hangs forever after copying (doesn't respond to user input).
